[package]
name = "hir"
version = "0.1.0"
edition = "2024"


[dependencies]
diagnostic = { path = "../diagnostic" }
ast = { path = "../ast" }
utils = { path = "../utils" }

serde.workspace = true
bimap.workspace = true
strum.workspace = true
strum_macros.workspace = true

[dev-dependencies]
indoc.workspace = true
tokenizer = { path = "../tokenizer" }
