//! Deprecated: a more general `Lookahead` struct is implemented in `lookahead.rs`
//! (ast crate) and should be used instead. This module is kept for "just in case".

use std::collections::VecDeque;

/// An iterator wrapper that supports rewinding over already-consumed items.
///
/// Has two modes:
///
/// - **Normal**: items are first drained from the internal buffer (if any),
///   then read directly from the inner iterator.
/// - **Recording**: items are read from the inner iterator as usual, but each
///   item is also cloned into the internal buffer.
///
/// Call [`start_recording`](BufferedIter::start_recording) to enter recording mode.
/// Call [`rewind`](BufferedIter::rewind) to exit recording mode and allow
/// consuming the recorded items.
/// Call [`release`](BufferedIter::release) to exit recording
/// mode and discard the recording when replay is not needed.
pub struct BufferedIter<I>
where
    I: Iterator,
    I::Item: Clone,
{
    inner: I,
    replay: VecDeque<I::Item>,
    recording: Vec<I::Item>,
    is_recording: bool,
    peeked: Option<I::Item>,
}

impl<I> BufferedIter<I>
where
    I: Iterator,
    I::Item: Clone,
{
    pub fn new(inner: I) -> Self {
        Self {
            inner,
            replay: VecDeque::new(),
            recording: Vec::new(),
            is_recording: false,
            peeked: None,
        }
    }

    pub fn peek(&mut self) -> Option<&I::Item> {
        if self.peeked.is_none() {
            self.peeked = self.replay.pop_front().or_else(|| self.inner.next());
        }
        self.peeked.as_ref()
    }

    pub fn start_recording(&mut self) {
        self.is_recording = true;
    }

    pub fn rewind(&mut self) {
        debug_assert!(self.is_recording, "Not in recording mode");
        for item in self.recording.drain(..) {
            self.replay.push_back(item);
        }
        self.is_recording = false;
    }

    pub fn release(&mut self) {
        self.is_recording = false;
        self.replay.clear();
        self.recording.clear();
    }
}

impl<I> Iterator for BufferedIter<I>
where
    I: Iterator,
    I::Item: Clone,
{
    type Item = I::Item;

    fn next(&mut self) -> Option<Self::Item> {
        let item = self
            .peeked
            .take()
            .or_else(|| self.replay.pop_front())
            .or_else(|| self.inner.next())?;
        if self.is_recording {
            self.recording.push(item.clone());
        }
        Some(item)
    }
}

// These tests are generated by AI (Claude Sonnet 4.6), validated by human.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normal_mode_reads_inner() {
        let mut iter = BufferedIter::new(1..=3);
        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.next(), Some(2));
        assert_eq!(iter.next(), Some(3));
        assert_eq!(iter.next(), None);
    }

    #[test]
    fn peek_does_not_consume_and_works_in_all_modes() {
        let mut iter = BufferedIter::new(1..=4);
        // normal mode: peek from inner
        assert_eq!(iter.peek(), Some(&1));
        assert_eq!(iter.peek(), Some(&1)); // stable
        assert_eq!(iter.next(), Some(1));

        // recording mode: peek must not skip items
        iter.start_recording();
        assert_eq!(iter.peek(), Some(&2));
        assert_eq!(iter.next(), Some(2)); // must be 2, not 3

        iter.rewind();
        // normal mode: peek from buffer after rewind
        assert_eq!(iter.peek(), Some(&2));
        assert_eq!(iter.next(), Some(2));

        // exhausted
        assert_eq!(iter.next(), Some(3));
        assert_eq!(iter.peek(), Some(&4));
        assert_eq!(iter.next(), Some(4));
        assert_eq!(iter.peek(), None);
        assert_eq!(iter.next(), None);
    }

    #[test]
    fn recording_forwards_items_and_fills_buffer() {
        let mut iter = BufferedIter::new(1..=3);
        iter.start_recording();
        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.next(), Some(2));
        // buffer holds [1, 2], inner still has 3
        assert_eq!(iter.recording.len(), 2);
    }

    #[test]
    fn rewind_replays_recorded_items() {
        let mut iter = BufferedIter::new(1..=4);
        iter.start_recording();
        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.next(), Some(2));
        iter.rewind();
        // replayed from buffer
        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.next(), Some(2));
        // buffer exhausted, back to inner
        assert_eq!(iter.next(), Some(3));
        assert_eq!(iter.next(), Some(4));
        assert_eq!(iter.next(), None);
    }

    #[test]
    fn release_discards_recording() {
        let mut iter = BufferedIter::new(1..=3);
        iter.start_recording();
        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.next(), Some(2));
        iter.release();
        // no replay, continues from inner
        assert_eq!(iter.next(), Some(3));
        assert_eq!(iter.next(), None);
    }

    #[test]
    fn rewind_then_record_again() {
        let mut iter = BufferedIter::new(1..=5);
        iter.start_recording();
        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.next(), Some(2));
        iter.rewind();
        // consume replayed items
        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.next(), Some(2));
        // record again from where inner left off
        iter.start_recording();
        assert_eq!(iter.next(), Some(3));
        iter.rewind();
        assert_eq!(iter.next(), Some(3));
        assert_eq!(iter.next(), Some(4));
        assert_eq!(iter.next(), Some(5));
        assert_eq!(iter.next(), None);
    }
}
