/// The same as `std::iter::Peekable`, but with a fixed-size lookahead buffer of size `N`.
pub struct Lookahead<I, const N: usize>
where
    I: Iterator,
{
    inner: I,
    lookahead: [Option<I::Item>; N],
}

impl<I, const N: usize> Lookahead<I, N>
where
    I: Iterator,
{
    pub fn new(mut inner: I) -> Self {
        Self {
            lookahead: std::array::from_fn(|_| inner.next()),
            inner,
        }
    }

    pub fn peek(&self) -> Option<&I::Item> {
        self.peek_nth(0)
    }

    pub fn peek_nth(&self, n: usize) -> Option<&I::Item> {
        debug_assert!(n < N, "Lookahead index out of bounds");
        self.lookahead.get(n)?.as_ref()
    }
}

impl<I, const N: usize> Iterator for Lookahead<I, N>
where
    I: Iterator,
{
    type Item = I::Item;

    fn next(&mut self) -> Option<Self::Item> {
        if N == 0 {
            return self.inner.next();
        }

        self.lookahead.rotate_left(1);
        std::mem::replace(&mut self.lookahead[N - 1], self.inner.next())
    }
}

// These tests are generated by AI (Gemini 3.5 Flash), validated by human.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_standard_flow() {
        let items = vec![10, 20, 30, 40];
        let mut iter = Lookahead::<_, 3>::new(items.into_iter());

        // Initial state: buffer should be fully populated
        assert_eq!(iter.peek(), Some(&10));
        assert_eq!(iter.peek_nth(1), Some(&20));
        assert_eq!(iter.peek_nth(2), Some(&30));

        // Consume one item: buffer shifts, new item enters from the back
        assert_eq!(iter.next(), Some(10));
        assert_eq!(iter.peek(), Some(&20));
        assert_eq!(iter.peek_nth(2), Some(&40));

        // Consume until iterator is exhausted
        assert_eq!(iter.next(), Some(20));
        assert_eq!(iter.next(), Some(30));
        assert_eq!(iter.next(), Some(40));

        // Buffer is completely drained
        assert_eq!(iter.next(), None);
        assert_eq!(iter.peek(), None);
    }

    #[test]
    fn test_short_iterator() {
        // Iterator has fewer items than the lookahead window N
        let items = vec![1, 2];
        let mut iter = Lookahead::<_, 4>::new(items.into_iter());

        // First elements are populated, trailing ones are None
        assert_eq!(iter.peek_nth(0), Some(&1));
        assert_eq!(iter.peek_nth(1), Some(&2));
        assert_eq!(iter.peek_nth(2), None);
        assert_eq!(iter.peek_nth(3), None);

        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.peek_nth(0), Some(&2));
        assert_eq!(iter.peek_nth(1), None);
    }

    #[test]
    fn test_empty_iterator() {
        let items: Vec<i32> = vec![];
        let mut iter = Lookahead::<_, 2>::new(items.into_iter());

        assert_eq!(iter.peek(), None);
        assert_eq!(iter.peek_nth(1), None);
        assert_eq!(iter.next(), None);
    }

    #[test]
    fn test_zero_window_size() {
        // Edge case: N = 0 should fallback to standard iterator behavior
        let items = vec![1, 2];
        let mut iter = Lookahead::<_, 0>::new(items.into_iter());

        assert_eq!(iter.next(), Some(1));
        assert_eq!(iter.next(), Some(2));
        assert_eq!(iter.next(), None);
    }
}
